# Generated by Django 3.0.6 on 2020-10-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(max_length=200)),
                ('location_name', models.CharField(max_length=200)),
                ('temp', models.CharField(max_length=200, null=True)),
                ('rh', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
