# Generated by Django 3.0.6 on 2020-10-28 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condition', '0001_initial'),
        ('make', '0001_initial'),
        ('model', '0001_initial'),
        ('calibration_frequency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_no', models.CharField(max_length=200)),
                ('ulr_no', models.CharField(max_length=200, null=True)),
                ('uncertainity', models.FloatField(blank=True, default=1)),
                ('issue_date', models.DateField()),
                ('exp_date', models.DateField()),
                ('review_of_record', models.BooleanField(default=False)),
                ('active_status', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='MasterInstrumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MasterInstrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_serialno', models.CharField(max_length=200, null=True)),
                ('master_idno', models.CharField(max_length=200, null=True)),
                ('range', models.CharField(max_length=200, null=True)),
                ('inservice_date', models.DateField(null=True)),
                ('inservice', models.BooleanField(default=False)),
                ('least_count', models.FloatField(default='', max_length=200)),
                ('resolution', models.FloatField(default='', max_length=200)),
                ('initial_trac', models.CharField(default='', max_length=200)),
                ('acceptance_criteria', models.CharField(default='', max_length=200)),
                ('purchase_from', models.CharField(default='', max_length=200)),
                ('purchase_order', models.CharField(default='', max_length=200)),
                ('purchase_date', models.DateField(null=True)),
                ('date_of_receipt', models.DateField(null=True)),
                ('condition_of_receipt', models.CharField(max_length=200, null=True)),
                ('date_of_inspection', models.DateField(null=True)),
                ('software_details', models.CharField(default='', max_length=200)),
                ('software_idno', models.CharField(default='', max_length=200)),
                ('software_inservice', models.CharField(default='', max_length=200)),
                ('manufacture_instruction', models.CharField(default='', max_length=200)),
                ('national_international_standerd', models.CharField(default='', max_length=200)),
                ('accuracy', models.FloatField(max_length=200, null=True)),
                ('amount', models.FloatField(max_length=200, null=True)),
                ('referance_standard', models.CharField(max_length=200, null=True)),
                ('ext_calibration_agency', models.CharField(max_length=200, null=True)),
                ('cal_frequency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calibration_frequency.CalibrationFrequency')),
                ('current_inst_condition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condition.Condition')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='make.Make')),
                ('master_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterinstrument.MasterInstrumentType')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.Model')),
            ],
        ),
    ]
