# Generated by Django 3.0.6 on 2020-10-28 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('make', '0001_initial'),
        ('masterinstrument', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='make',
            name='master_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masterinstrument.MasterInstrumentType'),
        ),
    ]
