# Generated by Django 3.0.6 on 2020-10-28 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_no', models.CharField(max_length=200)),
                ('dt_receipt', models.DateField()),
                ('total_inst', models.IntegerField()),
                ('gatepass', models.CharField(max_length=200)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Location')),
                ('party_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobinfo_party_name', to='contact.organization')),
            ],
        ),
    ]
