# Generated by Django 3.0.6 on 2020-11-04 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testing_info', '0001_initial'),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_number', models.CharField(max_length=200)),
                ('cert_date', models.DateField()),
                ('valid_date', models.DateField()),
                ('issue_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.organization')),
                ('inst_job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing_info.TestingInfo')),
            ],
        ),
    ]
