# Generated by Django 3.0.6 on 2020-10-28 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterinstrument', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target_Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workinstruction', models.CharField(max_length=200)),
                ('Is_Standard', models.CharField(max_length=200)),
                ('uncertainity', models.FloatField(blank=True, null=True)),
                ('master_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_instrument_master_name_1', to='masterinstrument.MasterInstrument')),
                ('master_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_instrument_master_name_2', to='masterinstrument.MasterInstrument')),
                ('master_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_instrument_master_name_3', to='masterinstrument.MasterInstrument')),
                ('target_instrument_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masterinstrument.MasterInstrumentType')),
            ],
        ),
    ]
