# Generated by Django 3.0.6 on 2020-10-28 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('model', '0001_initial'),
        ('unit', '0001_initial'),
        ('job_info', '0001_initial'),
        ('condition', '0001_initial'),
        ('uuc_info', '0001_initial'),
        ('make', '0002_make_master_name'),
        ('location', '0001_initial'),
        ('calibration_frequency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_job_id', models.CharField(max_length=200, null=True)),
                ('sr_no', models.CharField(max_length=200)),
                ('id_no', models.CharField(max_length=200)),
                ('least_count', models.FloatField(default='', max_length=200)),
                ('accuracy', models.FloatField()),
                ('low_range', models.FloatField()),
                ('high_range', models.FloatField()),
                ('inst_location', models.CharField(max_length=200)),
                ('nabl', models.BooleanField()),
                ('sp_req', models.CharField(max_length=200)),
                ('cal_frequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibration_frequency.CalibrationFrequency')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condition.Condition')),
                ('inst_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uuc_info.Target_Instrument')),
                ('job_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_info.JobInfo')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Location')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='make.Make')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.Model')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unit.Unit')),
            ],
        ),
    ]
